apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.nginx.secret.name }}
  namespace: {{ .Values.namespace.name }}
stringData:
  {{ .Values.nginx.configFile.name }}: |
    server {
      listen       ${NGINX_LISTEN_PORT};
      server_name  ${NGINX_LISTEN_SERVER};
  
      location /api/v1/users {
          proxy_pass ${AUTH_SERVICE_URL};
      }
      location /api/v1/auth {
          proxy_pass ${AUTH_SERVICE_URL};
      }
      location /api/v1/token {
          proxy_pass ${AUTH_SERVICE_URL};
      }

      location /api/v1/sheets {
          proxy_pass ${CORE_SERVICE_URL};
      }
      location /api/v1/tasks {
          proxy_pass ${CORE_SERVICE_URL};
      }

      location /api/v1/actions {
          proxy_pass ${ANALYTICS_SERVICE_URL};
      }
      location /api/v1/analytics {
          proxy_pass ${ANALYTICS_SERVICE_URL};
      }
    }
