apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace.name }}
stringData:
  NGINX_LISTEN_PORT: "{{ .Values.nginx.secret.port }}"
  NGINX_LISTEN_SERVER: "{{ .Values.nginx.secret.containerHost }}"
  AUTH_SERVICE_URL: "{{ .Values.nginx.secret.authUrl }}"
  CORE_SERVICE_URL: "{{ .Values.nginx.secret.coreUrl }}"
  ANALYTICS_SERVICE_URL: "{{ .Values.nginx.secret.analyticsUrl }}"
