apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace.name }}
stringData:
  WEB_CONTAINER_HOST: "{{ .Values.analytics.secret.containerHost }}"
  WEB_PORT: "{{ .Values.analytics.secret.port }}"
  WORKERS: "{{ .Values.analytics.secret.workers }}"
  SERVICES: "{{ .Values.database.secret.services }}"
  DEBUG: "{{ .Values.database.secret.debug }}"
  PERSISTENCE: "{{ .Values.database.secret.persistence }}"