apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace.name }}
stringData:
  ZOOKEEPER_HOST: "{{ .Values.zookeeper.secret.host }}"
  ZOOKEEPER_CLIENT_PORT: "{{ .Values.zookeeper.secret.port }}"
  ZOOKEEPER_TICK_TIME: "{{ .Values.zookeeper.secret.tickTime }}"
  KAFKA_ZOOKEEPER_CONNECT: "{{ .Values.zookeeper.secret.host }}:{{ .Values.zookeeper.secret.port }}"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://{{ .Values.kafka.secret.host }}.{{ .Values.namespace.name }}:{{ .Values.kafka.secret.port }}"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "{{ .Values.kafka.secret.replicas }}"
  KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: "{{ .Values.kafka.secret.replicas }}"
  KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: "{{ .Values.kafka.secret.replicas }}"
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "{{ .Values.kafka.secret.replicas }}"
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "{{ .Values.kafka.secret.replicas }}"
