apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace.name }}
stringData:
  POSTGRES_DB: "{{ .Values.database.secret.name }}"
  POSTGRES_HOST: {{ .Values.database.secret.host }}
  POSTGRES_PASSWORD: {{ .Values.database.secret.password }}
  POSTGRES_USER: {{ .Values.database.secret.user }}
  POSTGRES_PORT: "{{ .Values.database.secret.port }}"
  WEB_CONTAINER_HOST: {{ .Values.auth.secret.containerHost }}
  WEB_HOST: {{ .Values.auth.secret.host }}
  WEB_PORT: "{{ .Values.auth.secret.port }}"
  WORKERS: "{{ .Values.auth.secret.workers }}"
