---
# Source: test/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: nginx
---
# Source: test/templates/config.yaml
apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret-config
  namespace: nginx
stringData:
  default.conf.template: |
    server {
      listen       ${NGINX_LISTEN_PORT};
      server_name  ${NGINX_LISTEN_SERVER};
  
      location /api/v1/users {
          proxy_pass ${AUTH_SERVICE_URL};
      }
      location /api/v1/auth {
          proxy_pass ${AUTH_SERVICE_URL};
      }
      location /api/v1/token {
          proxy_pass ${AUTH_SERVICE_URL};
      }

      location /api/v1/sheets {
          proxy_pass ${CORE_SERVICE_URL};
      }
      location /api/v1/tasks {
          proxy_pass ${CORE_SERVICE_URL};
      }
      location /api/v1/statuses {
        proxy_pass ${CORE_SERVICE_URL};
      }

      location /api/v1/actions {
          proxy_pass ${ANALYTICS_SERVICE_URL};
      }
      location /api/v1/analytics {
          proxy_pass ${ANALYTICS_SERVICE_URL};
      }
    }
---
# Source: test/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: nginx
  namespace: nginx
stringData:
  NGINX_LISTEN_PORT: "80"
  NGINX_LISTEN_SERVER: "localhost"
  AUTH_SERVICE_URL: "http://todo-auth.todo-auth:8000"
  CORE_SERVICE_URL: "http://todo-core.todo-core:8000"
  ANALYTICS_SERVICE_URL: "http://todo-analytics.todo-analytics:8000"
---
# Source: test/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - name: nginx
    port: 80
    targetPort: 80
    nodePort: 30012
  selector:
    app: nginx
---
# Source: test/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.4
        ports:
        - containerPort: 80
        envFrom:
          - secretRef:
              name: nginx
        volumeMounts:
          - name: nginx-config-volume
            mountPath: /etc/nginx/templates/default.conf.template
            subPath: default.conf.template
            readOnly: true
      volumes:
        - name: nginx-config-volume
          secret:
            secretName: nginx-secret-config
