apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.database.persistentVolumeClaim.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  storageClassName: {{ .Values.storageClass.name }}
  accessModes:
    {{- toYaml .Values.database.persistentVolumeClaim.accessModes | nindent 4 }}
  resources:
    {{- toYaml .Values.database.persistentVolumeClaim.resources | nindent 4 }}